# Naive Bayes

## Problem Statement:
    
Prepare a classification model using Naive Bayes for salary Data.

In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix

from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB

In [2]:
train = pd.read_csv("C:/Users/BASHAR/OneDrive/Documents/Data Science/Assignment/Assignment - 12/SalaryData_Train.csv")
train.head()

age          workclass   education  educationno        maritalstatus  \
0   39          State-gov   Bachelors           13        Never-married   
1   50   Self-emp-not-inc   Bachelors           13   Married-civ-spouse   
2   38            Private     HS-grad            9             Divorced   
3   53            Private        11th            7   Married-civ-spouse   
4   28            Private   Bachelors           13   Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0        Adm-clerical   Not-in-family   White     Male         2174   
1     Exec-managerial         Husband   White     Male            0   
2   Handlers-cleaners   Not-in-family   White     Male            0   
3   Handlers-cleaners         Husband   Black     Male            0   
4      Prof-specialty            Wife   Black   Female            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            13   United-States   <=50K  
2            0            40   United-States   <=50K  
3            0            40   United-States   <=50K  
4            0            40            Cuba   <=50K

In [3]:
test = pd.read_csv("C:/Users/BASHAR/OneDrive/Documents/Data Science/Assignment/Assignment - 12/SalaryData_Test.csv")
test.head()

age   workclass      education  educationno        maritalstatus  \
0   25     Private           11th            7        Never-married   
1   38     Private        HS-grad            9   Married-civ-spouse   
2   28   Local-gov     Assoc-acdm           12   Married-civ-spouse   
3   44     Private   Some-college           10   Married-civ-spouse   
4   34     Private           10th            6        Never-married   

           occupation    relationship    race    sex  capitalgain  \
0   Machine-op-inspct       Own-child   Black   Male            0   
1     Farming-fishing         Husband   White   Male            0   
2     Protective-serv         Husband   White   Male            0   
3   Machine-op-inspct         Husband   Black   Male         7688   
4       Other-service   Not-in-family   White   Male            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            50   United-States   <=50K  
2            0            40   United-States    >50K  
3            0            40   United-States    >50K  
4            0            30   United-States   <=50K

## EDA on Train data

In [11]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30161 entries, 0 to 30160
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            30161 non-null  int64 
 1   workclass      30161 non-null  int32 
 2   education      30161 non-null  int32 
 3   educationno    30161 non-null  int64 
 4   maritalstatus  30161 non-null  int32 
 5   occupation     30161 non-null  int32 
 6   relationship   30161 non-null  int32 
 7   race           30161 non-null  int32 
 8   sex            30161 non-null  int32 
 9   capitalgain    30161 non-null  int64 
 10  capitalloss    30161 non-null  int64 
 11  hoursperweek   30161 non-null  int64 
 12  native         30161 non-null  int32 
 13  Salary         30161 non-null  object
dtypes: int32(8), int64(5), object(1)
memory usage: 2.3+ MB


In [12]:
train.isna().sum()

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [13]:
train[train.duplicated()].shape

(3258, 14)

In [14]:
train[train.duplicated()]

age  workclass  education  educationno  maritalstatus  occupation  \
326     33          2          9           13              2           3   
364     27          2          9           13              4           2   
518     24          2         11            9              4           5   
525     24          2         11            9              4           2   
619     33          2          9           13              2           3   
...    ...        ...        ...          ...            ...         ...   
30110   47          2         11            9              2           2   
30118   20          2         11            9              4           6   
30132   22          2         15           10              4           0   
30157   40          2         11            9              2           6   
30159   22          2         11            9              4           0   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  \
326               0     4    1            0            0            40   
364               1     4    1            0            0            50   
518               4     2    0            0            0            40   
525               3     4    1            0            0            40   
619               0     4    1            0            0            40   
...             ...   ...  ...          ...          ...           ...   
30110             0     4    1            0            0            40   
30118             3     4    1            0            0            40   
30132             3     4    1            0            0            40   
30157             0     4    1            0            0            40   
30159             3     4    1            0            0            20   

       native  Salary  
326        37    >50K  
364        37   <=50K  
518        37   <=50K  
525        37   <=50K  
619        37    >50K  
...       ...     ...  
30110      37   <=50K  
30118      37   <=50K  
30132      37   <=50K  
30157      37    >50K  
30159      37   <=50K  

[3258 rows x 14 columns]

In [15]:
train1 = train.drop_duplicates()
train1.iloc[325:330]

age  workclass  education  educationno  maritalstatus  occupation  \
325   26          2         11            9              2           7   
327   46          1          1            7              2          13   
328   38          0         11            9              2           0   
329   65          2          1            7              6           7   
330   40          2          8           11              2          12   

     relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  \
325             0     4    1            0            0            40      37   
327             0     4    1            0            0            30      37   
328             0     4    1            0            0            40      37   
329             4     3    1            0            0            40      37   
330             0     4    1            0            0            40      37   

     Salary  
325   <=50K  
327   <=50K  
328    >50K  
329   <=50K  
330    >50K

In [16]:
train2 = train1.reset_index()
train2 = train2.drop(columns="index")
train2.iloc[325:330]

age  workclass  education  educationno  maritalstatus  occupation  \
325   26          2         11            9              2           7   
326   46          1          1            7              2          13   
327   38          0         11            9              2           0   
328   65          2          1            7              6           7   
329   40          2          8           11              2          12   

     relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  \
325             0     4    1            0            0            40      37   
326             0     4    1            0            0            30      37   
327             0     4    1            0            0            40      37   
328             4     3    1            0            0            40      37   
329             0     4    1            0            0            40      37   

     Salary  
325   <=50K  
326   <=50K  
327    >50K  
328   <=50K  
329    >50K

In [17]:
labelencoder = LabelEncoder()
names = train2[["workclass", "education", "maritalstatus", "occupation", "relationship", "race", "sex", "native", "Salary"]]

In [18]:
for i in names:
    train2[i] = labelencoder.fit_transform(train2[i])
    
train2.head()

age  workclass  education  educationno  maritalstatus  occupation  \
0   39          5          9           13              4           0   
1   50          4          9           13              2           3   
2   38          2         11            9              0           5   
3   53          2          1            7              2           5   
4   28          2          9           13              2           9   

   relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  \
0             1     4    1         2174            0            40      37   
1             0     4    1            0            0            13      37   
2             1     4    1            0            0            40      37   
3             0     2    1            0            0            40      37   
4             5     2    0            0            0            40       4   

   Salary  
0       0  
1       0  
2       0  
3       0  
4       0

## EDA on Test data

In [20]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15060 entries, 0 to 15059
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            15060 non-null  int64 
 1   workclass      15060 non-null  int32 
 2   education      15060 non-null  int32 
 3   educationno    15060 non-null  int64 
 4   maritalstatus  15060 non-null  int32 
 5   occupation     15060 non-null  int32 
 6   relationship   15060 non-null  int32 
 7   race           15060 non-null  int32 
 8   sex            15060 non-null  int32 
 9   capitalgain    15060 non-null  int64 
 10  capitalloss    15060 non-null  int64 
 11  hoursperweek   15060 non-null  int64 
 12  native         15060 non-null  int32 
 13  Salary         15060 non-null  object
dtypes: int32(8), int64(5), object(1)
memory usage: 1.1+ MB


In [21]:
test.isna().sum()

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [22]:
test[test.duplicated()].shape

(930, 14)

In [23]:
test[test.duplicated()]

age  workclass  education  educationno  maritalstatus  occupation  \
551     59          2         11            9              0           7   
601     32          2         11            9              2          11   
681     40          2         11            9              2           2   
799     24          2          9           13              4           9   
1044    44          2         14           15              2           9   
...    ...        ...        ...          ...            ...         ...   
15043   51          2         11            9              2           2   
15044   22          2         15           10              4           2   
15049   32          2         11            9              2           5   
15052   31          2         11            9              2           2   
15053   25          2         11            9              4           7   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  \
551               1     4    0            0            0            40   
601               0     4    1            0            0            40   
681               0     4    1            0            0            40   
799               1     4    1            0            0            35   
1044              0     4    1        99999            0            60   
...             ...   ...  ...          ...          ...           ...   
15043             0     4    1            0            0            40   
15044             3     4    1            0            0            40   
15049             0     4    1            0            0            40   
15052             0     4    1            0            0            40   
15053             3     4    0            0            0            40   

       native  Salary  
551        37   <=50K  
601        37   <=50K  
681        37   <=50K  
799        37   <=50K  
1044       37    >50K  
...       ...     ...  
15043      37   <=50K  
15044      37   <=50K  
15049      37   <=50K  
15052      37   <=50K  
15053      37   <=50K  

[930 rows x 14 columns]

In [24]:
test1 = test.drop_duplicates()
test1.iloc[550:555]

age  workclass  education  educationno  maritalstatus  occupation  \
550   49          2          9           13              2           3   
552   38          2         11            9              5           6   
553   50          3         15           10              2          11   
554   51          3         15           10              2           2   
555   22          2         15           10              4           6   

     relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  \
550             0     4    1            0            0            50      37   
552             4     2    0            0            0            28      37   
553             0     4    1            0            0            55      37   
554             0     4    1            0         1672            55      37   
555             3     1    1            0            0            35      37   

     Salary  
550    >50K  
552   <=50K  
553   <=50K  
554   <=50K  
555   <=50K

In [25]:
test2 = test1.reset_index()
test2 = test2.drop(columns="index")
test2.iloc[550:555]

age  workclass  education  educationno  maritalstatus  occupation  \
550   49          2          9           13              2           3   
551   38          2         11            9              5           6   
552   50          3         15           10              2          11   
553   51          3         15           10              2           2   
554   22          2         15           10              4           6   

     relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  \
550             0     4    1            0            0            50      37   
551             4     2    0            0            0            28      37   
552             0     4    1            0            0            55      37   
553             0     4    1            0         1672            55      37   
554             3     1    1            0            0            35      37   

     Salary  
550    >50K  
551   <=50K  
552   <=50K  
553   <=50K  
554   <=50K

In [26]:
labelencoder = LabelEncoder()
names = test2[["workclass", "education", "maritalstatus", "occupation", "relationship", "race", "sex", "native", "Salary"]]

In [27]:
for i in names:
    test2[i] = labelencoder.fit_transform(test2[i])
    
test2.head()

age  workclass  education  educationno  maritalstatus  occupation  \
0   25          2          1            7              4           6   
1   38          2         11            9              2           4   
2   28          1          7           12              2          10   
3   44          2         15           10              2           6   
4   34          2          0            6              4           7   

   relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  \
0             3     2    1            0            0            40      37   
1             0     4    1            0            0            50      37   
2             0     4    1            0            0            40      37   
3             0     2    1         7688            0            40      37   
4             1     4    1            0            0            30      37   

   Salary  
0       0  
1       0  
2       1  
3       1  
4       0

## Train & Test Split

In [28]:
x_train = train2.iloc[:, 0:13]
y_train = train2.iloc[:, 13]
x_test = test2.iloc[:, 0:13]
y_test = test2.iloc[:, 13]

## Normalization

In [29]:
def norm_func (i):
    x = (i-i.min())/(i.max()-i.min())
    return (x)

In [30]:
x_train = norm_func(x_train)
x_test =  norm_func(x_test)

## Building model using Gaussian Naive Bayes

In [33]:
gb = GaussianNB()
gb.fit(x_train, y_train)

GaussianNB()

In [34]:
pred_gb = gb.predict(x_test)
pred_gb

array([0, 0, 0, ..., 0, 1, 0])

In [36]:
confusion_matrix(y_test, pred_gb)

array([[10030,   590],
       [ 2296,  1214]], dtype=int64)

In [37]:
accuracy = accuracy_score(y_test, pred_gb)
print((accuracy)*100)

79.57537154989384


In [40]:
print("The accuracy of the Gaussian Naive Bayes classifier on training data is {:.2f} out of 1".format(gb.score(x_train, y_train)*100))

print("The accuracy of the Gaussian Naive Bayes classifier on test data is {:.2f} out of 1".format(gb.score(x_test, y_test)*100))

The accuracy of the Gaussian Naive Bayes classifier on training data is 79.56 out of 1
The accuracy of the Gaussian Naive Bayes classifier on test data is 79.58 out of 1


## Building model using Multinomial Naive Bayes

In [42]:
mb = MultinomialNB()
mb.fit(x_train, y_train)

MultinomialNB()

In [43]:
pred_mb = mb.predict(x_test)
pred_mb

array([0, 0, 0, ..., 0, 0, 0])

In [44]:
confusion_matrix(y_test, pred_mb)

array([[10616,     4],
       [ 3425,    85]], dtype=int64)

In [45]:
accuracy = accuracy_score(y_test, pred_mb)
print((accuracy)*100)

75.73248407643312


In [46]:
print("The accuracy of the Multinomial Naive Bayes classifier on training data is {:.2f} out of 1".format(mb.score(x_train, y_train)*100))

print("The accuracy of the Multinomial Naive Bayes classifier on test data is {:.2f} out of 1".format(mb.score(x_test, y_test)*100))

The accuracy of the Multinomial Naive Bayes classifier on training data is 74.99 out of 1
The accuracy of the Multinomial Naive Bayes classifier on test data is 75.73 out of 1


## Conclusion

GaussianNB Model has a better Accuracy, Thus we will use GaussianNB Classifier on Salary data.